spring:
  application:
    name: apisl.handson.entraid.msal

  cloud:
    azure:
      active-directory:
        enabled: true
        application-type: WEB_APPLICATION
        profile:
          tenant-id: ${ENTRA_TENANT_ID}
        credential:
          client-id: ${ENTRA_U2M_CLIENT_ID}
          client-secret: ${ENTRA_U2M_CLIENT_SECRET}
        authorization-clients:
          my-client-u2m:
            authorization-grant-type: authorization_code
            scopes:
              - openid
              - profile
              - offline_access

  session:
    store-type: redis
    redis:
      namespace: spring:session:msal-handson
      flush-mode: immediate
  data:
    redis:
      host: redis
      port: 6379
      # password:
