services:

  # Ollama
  ollama:
    container_name: ollama
    hostname: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - internal
      - external
    restart: unless-stopped

volumes:
  ollama-data:
