# Use Eclipse Temurin JDK 21 as the base image
FROM eclipse-temurin:21

# Set the working directory to /webui
WORKDIR /webapp

# Copy the webui directory from the source location
COPY . /webapp/

# Execute Gradle commands in order
RUN ./gradlew clean && \
    ./gradlew assemble
